# Generated by Django 4.1.4 on 2022-12-12 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('sku', models.CharField(max_length=255, unique=True, verbose_name='sku')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, null=True, verbose_name='price')),
                ('status', models.CharField(choices=[('in_stock', 'in stock'), ('on_order', 'on order'), ('expected', 'expected to arrive'), ('out_of_stock', 'out of stock'), ('not_produced', 'not produced')], default='in_stock', max_length=20, verbose_name='status')),
                ('image', models.ImageField(blank=True, upload_to='images/', verbose_name='image')),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'products',
                'ordering': ['title'],
            },
        ),
    ]
